### ISSUE TITLE
Adding my repository 1

### ISSUE THREAD

**Issue by bacloud14** [vinitshahdeo/Hacktoberfest2021#12]
### Information

- Issue: https://github.com/bacloud14/Classified-ads-48/issues/8
- Repository: https://github.com/bacloud14/Classified-ads-48
- Tech stack: JavaScript, NodeJs, MongoDB, Leaflet.

- [x] is it a `beginner-friendly` issue?

- Note: I would like to add the whole repository.

**Comment by thisisamank** [comment]
Looks good to me.
Can you create a PR with your issue?

**Comment by bacloud14** [comment]
I did
