### ISSUE TITLE
Adding my repository 2

### ISSUE THREAD

**Issue by bacloud14** [vinitshahdeo/Hacktoberfest2021#13]
### Information

- Issue: https://github.com/bacloud14/WeatherVenue/issues/40
- Repository: https://github.com/bacloud14/WeatherVenue/
- Tech stack: JavaScript, NodeJs, Redis, Google Maps.

- [x] is it a `beginner-friendly` issue?

- Note: I would like to add the whole repository.

**Comment by thisisamank** [comment]
can you create a PR with your issue for this?

**Comment by bacloud14** [comment]
I will 😃
