### ISSUE TITLE
My Interesting projects That I think can be added.

### ISSUE THREAD

**Issue by wimpywarlord** [vinitshahdeo/Hacktoberfest2021#159]
Here is the list. To understand the Project, go through the repo.

@vinitshahdeo @iamdevvalecha 

1) Good Morning Girlfriend - https://github.com/wimpywarlord/Goodmorning-Girlfriend
Tech Used - Vue.js, EJS, Node.js, Cron Jobs, NodeMailer Etc.

2) Amigos - https://github.com/wimpywarlord/Amigos
Tech Used - MongoDB, Async Programming, Jitsi Meet Etc. 

3) Study Buddy - https://github.com/wimpywarlord/Study-Buddy
Tech Used - Whatsapp API, EJS, Javascript, HTML

4) AutoDocs - https://github.com/wimpywarlord/AutoDoc
Tech Used - Solidity, Ethereum Rinky Test Net, Remix IDE, Ethereum Faucets, Application Binary Interface (ABI), Smart Contracts, Web3.js, Truffle.js, Ganache Etc. 

5) Btech Blueprint - https://github.com/wimpywarlord/BTech-Blueprint
Tech Used - EJS, CSS, Javascript, Bootstrap, Node.js, Express.js Etc.

6) My portfolio Website - https://github.com/wimpywarlord/wimpywarlord.github.io
Tech Used - SCSS, HTML, CSS, Javascript Etc.

I would love to help out students learn in the process.

**Comment by iamdevvalecha** [comment]
@wimpywarlord thanks!

**Comment by wimpywarlord** [comment]
They are all hosted websites and you can even use them in real-time (Link in Repo), Thanks for considering my projects.
