### ISSUE TITLE
Create a cover image for blog post

### ISSUE THREAD

**Issue by vinitshahdeo** [vinitshahdeo/Hacktoberfest2021#16]
@pranjalbareth

As discussed, please create a cover image and raise a PR by putting the exported `.jpg` and `.png` inside `/assets` directory.

Recommended dimensions: `1200px` width and `630px` height

**Comment by pranjalbareth** [comment]
Yea, Sure. Will do.

**Comment by vinitshahdeo** [comment]
Thank you so much @pranjalbareth 👏 

PS: The blog is out [here](https://vinitshahdeo.dev/beginner-friendly-issues-for-hacktoberfest-2021)!
