### ISSUE TITLE
PR Request Template link is broken

### ISSUE THREAD

**Issue by deephunt3r** [vinitshahdeo/Hacktoberfest2021#206]
Hey ! The PR Request Template for adding names to MENTORS.md  link in the README is not working(broken) the broken link - https://github.com/vinitshahdeo/Hacktoberfest2021/blob/main/.github/PULL_REQUEST_TEMPLATE/ADD_NEW_MENTOR.md

Maintainers can add a good first issue for beginners to contribute

![image](https://user-images.githubusercontent.com/60481830/134810524-a5bec69d-b9db-4fbe-bfe7-981814d6d848.png)

**Comment by vinitshahdeo** [comment]
Nice catch! Thanks for raising this.
I have fixed this now, can you please check it?

**Comment by vinitshahdeo** [comment]
RCA: It happened due to a bad [commit](https://github.com/vinitshahdeo/Hacktoberfest2021/commit/8f6171a20e2cdc761085d9a84d89e1b9dda90837#diff-fa426dd17a674108e6aef367b7529e5ce9e4d3a97ccb88724e8da9c6db1f8dc5).
cc/ @iamdevvalecha

**Comment by deephunt3r** [comment]
> Nice catch! Thanks for raising this.
> I have fixed this now, can you please check it?

Yeah! It's fixed now Thanks !!

**Comment by iamdevvalecha** [comment]
@vinitshahdeo @deephunt3r  sorry for mistake.

**Comment by deephunt3r** [comment]
> @vinitshahdeo @deephunt3r sorry for mistake.

no worries 😄

**Comment by deephunt3r** [comment]
I hope we can close this! Thanks for your contributions to the community 💯
