### ISSUE TITLE
Discord Link is broken

### ISSUE THREAD

**Issue by deephunt3r** [vinitshahdeo/Hacktoberfest2021#209]
Hey @vinitshahdeo The discord invite was expired in the README and in the blog too!

**Comment by vinitshahdeo** [comment]
Thanks @deephunt3r for pointing this out. I have fixed it at both places. Can you please verify once and mark it closed?

**Comment by deephunt3r** [comment]
@vinitshahdeo Yeah! It's working fine now and joined the server 🚀 
we can close this now
