### ISSUE TITLE
Request to add myself as a mentor 

### ISSUE THREAD

**Issue by xkeshav** [vinitshahdeo/Hacktoberfest2021#222]
Apologies for writing everything on title (corrected)  and submitting it from mobile.

I find it difficult where to raise PR

**Comment by xkeshav** [comment]
Name: Keshav Mohta LinkedIn: [xkeshav](https://linkedin.com/in/xkeshav) Twitter: [xkeshav](https://twitter.com/xkeshav) About:  
Currently working as a UI Lead at Barclays and having good understanding of JavaScript and TypeScript. 

Reason: Fan of better and neat coding practices with standard and recommended style guide and better documentation, having 50k reputation over stackoverflow.

**Comment by iamdevvalecha** [comment]
@xkeshav done.
