### ISSUE TITLE
Invalid discord link in action items for mentors  and  issue in Projects.md file

### ISSUE THREAD

**Issue by Jassi10000** [vinitshahdeo/Hacktoberfest2021#244]
@vinitshahdeo Sir , the link in the action item for mentors to join Discord is invalid , can you pls update the link that so that we all mentors can get into a place to ask things and discuss issues and problems .

Its a request to get it corrected soon. 

Sir I would also like to highlight that some projects that are getting merged in the PROJECTS.md  have 0 acitve issues . So it maybe a chance that are inactive . So can you make a announcement for the same so that we all mentors only include projects which is active and has a good amount of issues and PRs on it . 
Otherwise if mentees found an inactive project , after their contributions too , they will not be able to contribute actively due to project being inactive

**Comment by iamdevvalecha** [comment]
@Jassi10000
Part 1 is fixed.
>>>
Part 2 
projects with less no of issues can be shifted to bottom down.
@vinitshahdeo may be vinit bhai can provide better solution
