### ISSUE TITLE
Discord Invite Link is not working

### ISSUE THREAD

**Issue by wimpywarlord** [vinitshahdeo/Hacktoberfest2021#259]
The discord invite link mentioned in the pinned issue is not working, and hence I am unable to join the server.

Pinned issue : https://github.com/vinitshahdeo/Hacktoberfest2021/issues/140

![Screenshot_1](https://user-images.githubusercontent.com/41532804/134956831-0ad6a923-9f69-46a5-a52f-6313a880dd7b.png)

**Comment by iamdevvalecha** [comment]
@wimpywarlord hey , https://discord.com/invite/MgA48yUjVK try to open this again.

**Comment by iamdevvalecha** [comment]
it's working for me.
![Screenshot from 2021-09-28 00-11-41](https://user-images.githubusercontent.com/71969867/134966781-06a1bebc-2ae8-46e4-94ae-43aa0580da97.png)
