### ISSUE TITLE
Greet the first time users who raise an issue or a PR

### ISSUE THREAD

**Issue by shvam0000** [vinitshahdeo/Hacktoberfest2021#320]
Since this repository is for first-timers, we can use GitHub Actions to greet them when they raise their first issue or open their first pull request in this repository. I'd like to take this issue.

**Comment by Jassi10000** [comment]
@shvam0000  Buddy this repo is not for Hacktoberfest contributions 
Its just for mentors to colloborate and prepare resouces , issues and projects to which mentees can contribute the whole HacktoberFest month

**Comment by shvam0000** [comment]
Okay, closing this issue then, Thank you!
