### ISSUE TITLE
Invalid Issues link in ISSUES.md

### ISSUE THREAD

**Issue by AkshayHere** [vinitshahdeo/Hacktoberfest2021#374]
Issue #83 Github LookBook is pointing to an invalid Issues URL.

https://github.com/vinitshahdeo/GitHubLookBook/issues/37

Please help fix this URL to point to the correct issue.

**Comment by Jassi10000** [comment]
@AkshayHere Thanks buddy for highlighting that out , give me a few minutes 
I'll update that 
Till that you can try some other nice issues as well 
All the best !!!

**Comment by Jassi10000** [comment]
@AkshayHere I have made the PR , it will get corrected soon

**Comment by AkshayHere** [comment]
> 
> 
> @AkshayHere Thanks buddy for highlighting that out , give me a few minutes I'll update that Till that you can try some other nice issues as well All the best !!!

Thanks @Jassi10000. I will checkout :)
