### ISSUE TITLE
Request for an event

### ISSUE THREAD

**Issue by mriceflame** [vinitshahdeo/Hacktoberfest2021#42]
### Please provide the following information

- **Is this event for college students or professionals?** 
University Students

- **How many folks do you expect will attend this event?** <Add expected number>
500
- **When do you want this event?** <Add date>
24th October
- **Language of the event?** <Add language>
English/Hindhi
- [ ] fill [this](https://forms.gle/7FQtAnFVJESSFXJ3A) google form.
ok

**Comment by vinitshahdeo** [comment]
@mriceflame Thanks for requesting an event. Please let us know the timing?

**Comment by mriceflame** [comment]
Can you share some details, what type of event you can host?

**Comment by mriceflame** [comment]
@vinitshahdeo can we have this event on first october? , 7-10 pm ist, any slot in that time will work

**Comment by mriceflame** [comment]
Actually i am organizing a hackathon at those dates, and wanted to have it during that, but it is last week of october, it will  be good for folks if we have it in the start too.
