### ISSUE TITLE
Invalid discord link 

### ISSUE THREAD

**Issue by hritik5102** [vinitshahdeo/Hacktoberfest2021#457]
### Please provide the following information

Discord link is invalid cc @vinitshahdeo 

![image](https://user-images.githubusercontent.com/44053202/135745178-4447307a-7247-45da-b28e-6e859eb8a65b.png)

Reference: https://vinitshahdeo.dev/hacktoberfest-2021

**Comment by shreya-gb** [comment]
Hello, I can work on this. May I?

**Comment by sreekaransrinath** [comment]
Doesn't look like there's anything to work on here @shreya-gb. I've mentioned a link that works in the replies for mentors action items.
https://github.com/vinitshahdeo/Hacktoberfest2021/issues/140
