### ISSUE TITLE
Request for an event

### ISSUE THREAD

**Issue by divya520357** [vinitshahdeo/Hacktoberfest2021#520]
### Please provide the following information

- **Is this event for college students or professionals?** College students

- **How many folks do you expect will attend this event?** <70>

- **When do you want this event?** <15th Oct, 2021>

- **Language of the event?** English or a mix of English and Hindi

- [x] fill [this](https://forms.gle/7FQtAnFVJESSFXJ3A) google form.

**Comment by thisisamank** [comment]
Hi @divya520357 if you have filled the form then someone from the team will get back to you soon.
